# Change these first
owner: kaluaim # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: kalua.im
    url: https://kalua.im

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.kalua.im
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: kaluaimUpptime
  introTitle: "**Hi**."
  introMessage: "---"
  navbar:
    - title: Status
      href: /
    - title: Issues
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
